version: '3.5'
services:
  db:
    image: mysql:5.7
    command: --log_error_verbosity=1
    volumes:
      - ./temp/database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academy
      MYSQL_USER: academy
      MYSQL_PASSWORD: academy
        
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306